name: best_buy_api
description: A Best Buy API Client.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  pedantic: ^1.11.1
  http: ^0.13.4
  meta: ^1.7.0


dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  test: ^1.21.1